Fix/url
Star-Academy/Summer1403-Project-Group03-Frontend pull request #39
Opened 2024-08-31 15:48 UTC by asAlwaysZahra

fix api urls

2024-09-04 06:53 UTC, mojerf requested changes

2024-09-04 06:53 UTC, mojerf commented on src/app/graph/components/category/category.component.ts
> +    if (this.nameValue != '') {
این به صورت 

`if (!this.nameValue) {return;}`
باشه بهتره

2024-09-04 06:53 UTC, mojerf commented on src/app/guards/auth/auth.guard.ts
> +          // }
این چرا کامنت شده؟

2024-09-04 06:53 UTC, mojerf commented on src/app/guards/permissions/permission.guard.ts
> +        return !!permissions?.permission.includes(requiredPermission);
دو تا ! واسه چیه؟

2024-09-04 06:53 UTC, mojerf commented on src/app/user/components/login/login.component.ts
> +  isRecoverMode = true;
این واسه ریکاور پسورده؟ اگه آره بهتر نیست یه کامپوننت و URL جدا باشه

2024-09-04 09:04 UTC, asAlwaysZahra commented on src/app/guards/auth/auth.guard.ts
> +          // }
بک قسمت پرمیشن مشکل داشت، لاگین انجام میشد ولی navigate نه. موقتا کامنت شده

2024-09-04 09:05 UTC, asAlwaysZahra commented on src/app/guards/permissions/permission.guard.ts
> +        return !!permissions?.permission.includes(requiredPermission);
معادل همون شرط قبلی هست، خود ide پیشنهاد داد

2024-09-04 09:05 UTC, asAlwaysZahra commented on src/app/user/components/login/login.component.ts
> +  isRecoverMode = true;
آره داشتم به همین فکر میکردم

2024-09-05 01:10 UTC, mojerf approved these changes

2024-09-05 09:30 UTC, merged